[project]
name = "cuda-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "verifiers>=0.1.3.post0",
    "torch>=2.0.0",
    "datasets",
    "pandas",
    "numpy",
]
